## Библиотеки

In [1]:
import numpy as np
import pandas as pd
import requests

from sklearn.ensemble import RandomForestClassifier, RandomForestRegressor
#from sklearn.linear_model import SGDClassifier
from sklearn.svm import SVR, SVC
from sklearn.model_selection import GridSearchCV

In [2]:
from sklearn.datasets import make_classification, make_regression

## Данные

In [3]:
X, y = make_classification(n_samples=1000, n_features=4,
                           n_informative=2, n_redundant=0,
                            random_state=0, shuffle=True)

In [4]:
Z, r = make_regression(n_samples=1000, n_features=10,
                           n_informative=4, random_state=0, shuffle=True)

- Дефолтные параметры
- Подбор параметров
- Предсказание

## Запросы к приложению

In [537]:
r_n = requests.get('http://0.0.0.0:8080/api/ml_models') #/192.168.1.61
r_n

ConnectionError: HTTPConnectionPool(host='0.0.0.0', port=8080): Max retries exceeded with url: /api/ml_models (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7fbe8b609100>: Failed to establish a new connection: [Errno 61] Connection refused'))

In [528]:
#currp = r_n.json()

In [529]:
#currp2 = r_n.json()

In [530]:
r_n.json()['data'][0]

{'classification': ['Random Forest', 'SVM'],
 'regression': ['Random Forest', 'SVM']}

In [531]:
r_n.json()['data'][1]

{'data': [{'X': [[-0.7847847290606281,
     -0.17012230475116602,
     1.754650332312673,
     1.9021556191316682],
    [0.5355105697391037,
     -0.3995688603234003,
     0.9991473474617917,
     -0.7860574303746627],
    [0.40713033108324814,
     -0.6285575802445897,
     -1.1419705321461509,
     -1.1242990445411827],
    [0.06478573929391421,
     0.9448600019930663,
     2.7574918734703444,
     1.4248587207955743],
    [-1.402330532885283,
     -0.3070684868414365,
     -0.04100741104344352,
     1.3790022377141293],
    [1.0222103545858243,
     -0.4174294563419882,
     -3.2167564338087895,
     1.0333155868384027],
    [-1.216076580745861,
     0.14067190330796092,
     -0.8605758080648516,
     -1.0153027538179111],
    [0.8779241693247446,
     1.1037740024936882,
     0.492419303187699,
     1.331433716523474],
    [-0.9330778408941012,
     -0.2387763168452323,
     0.1454436627382012,
     -1.6950211864803033],
    [1.0857972247059309,
     -1.3811000860829576,
     2.20

In [532]:
# [s['model_path'] for s in r_n.json()['data'][1]['data']], 
[s['id'] for s in r_n.json()['data'][1]['data']]

[1, 2]

In [523]:
data={'problem': 'classification', 'name': 'Random_Forest', 'h_tune': False, 'X':X.tolist(), 'y':y.tolist()}

In [524]:
requests.post('http://0.0.0.0:8080/api/ml_models', json=data)

<Response [200]>

In [525]:
data={'problem': 'classification', 'name': 'SVM', 'h_tune': False, 'X':X.tolist(), 'y':y.tolist()}

In [526]:
requests.post('http://0.0.0.0:8080/api/ml_models', json=data)

<Response [200]>

In [536]:
requests.delete('http://0.0.0.0:8080/api/ml_models/7')

<Response [204]>

In [305]:
requests.put('http://0.0.0.0:8080/api/ml_models/4', 
             json={'problem': 'classification', 'name': 'Random_Forest', 'h_tune': True})

<Response [500]>

In [306]:
requests.put('http://0.0.0.0:8080/api/ml_models/2', 
             json={'problem': 'classification', 'name': 'Random_Forest', 'h_tune': False})

KeyboardInterrupt: 

In [469]:
requests.put('http://0.0.0.0:8080/api/ml_models/4', 
             json={'problem': 'classification', 'name': 'SVM', 'h_tune': False})

<Response [200]>

#### Предсказание

In [533]:
r_n = requests.get('http://0.0.0.0:8080/api/ml_models/1') #/192.168.1.61
r_n

<Response [200]>

In [534]:
r_n.json()

[1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 1,
 0,
 1,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 1,


## MLflow

In [ ]:
mlflow server --host 0.0.0.0 --backend-store-uri sqlite:///ml.db --default-artifact-root ./mlartifacts

## Модели

In [226]:
def Classification(model, X, y, htune=False):
    
    if model == 'Random Forest':
        param_grid = {'n_estimators': [50, 100], 'max_depth': [3, 4], 'max_features': ['auto', 'sqrt']}
        clf = RandomForestClassifier(random_state=0)
    elif model == 'SVM':
        param_grid = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
        clf = SVC(random_state=0)
    
    if htune:
        clf_CV = GridSearchCV(estimator=clf, param_grid=param_grid, cv= 5)
        clf_CV.fit(X, y)
        #best_params = clf.best_params_
        best_model = clf_CV.best_estimator_
        prediction = best_model.predict(X)
        
    else:
        clf.fit(X, y)
        prediction = clf.predict(X)
        #best_params = clf.get_params()
    
    return prediction #best_params

In [227]:
%%time
prediction = Classification('SVM', X, y, False)
prediction[:10]

CPU times: user 32.3 ms, sys: 8.44 ms, total: 40.7 ms
Wall time: 44.4 ms


array([1, 0, 0, 1, 1, 1, 0, 1, 0, 1])

In [228]:
def Regression(model, X, y, htune=False):
    
    if model == 'Random Forest':
        param_grid = {'n_estimators': [50, 100], 'max_depth': [3, 4], 'max_features': ['auto', 'sqrt']}
        lr = RandomForestRegressor(random_state=0)
    elif model == 'SVM':
        param_grid = {'kernel':('linear', 'rbf'), 'C':[1, 10]}
        lr = SVR()
    
    if htune:
        lr_CV = GridSearchCV(estimator=lr, param_grid=param_grid, cv= 5)
        lr_CV.fit(X, y)
        #best_params = clf.best_params_
        best_model = lr_CV.best_estimator_
        prediction = best_model.predict(X)
        
    else:
        lr.fit(X, y)
        prediction = lr.predict(X)
        #best_params = clf.get_params()
    
    return prediction #best_params

In [229]:
%%time
prediction = Regression('Random Forest', Z, r, False)
prediction[:10]

CPU times: user 490 ms, sys: 16.7 ms, total: 506 ms
Wall time: 509 ms


array([  42.71988408,  -42.73897822,   26.25876795,   48.71589377,
         -4.2270664 ,  -80.92470981,   56.38980455,   46.08721386,
       -140.80379108,   33.87466928])

#### Random Forest

classification

In [230]:
#Random forest GreesSearchCV
rf_param_grid = {'n_estimators': [50, 100],
                 'max_depth': [3, 4],
                 'max_features': ['auto', 'sqrt']
                }

In [231]:
%%time
clf = RandomForestClassifier(random_state=0)
CV_clf = GridSearchCV(estimator=clf, param_grid=rf_param_grid, cv= 5)
CV_clf.fit(X, y)
best_params = CV_clf.best_params_
best_model = CV_clf.best_estimator_
prediction = best_model.predict(X)

CPU times: user 4.15 s, sys: 68.3 ms, total: 4.22 s
Wall time: 4.26 s


In [234]:
CV_clf.score(X, y)

0.968

regression

In [238]:
%%time
lr = RandomForestRegressor(random_state=0)
CV_lr = GridSearchCV(estimator=lr, param_grid=rf_param_grid, cv= 5)
CV_lr.fit(Z, r)
best_params = CV_lr.best_params_
best_model = CV_lr.best_estimator_
prediction = best_model.predict(Z)

CPU times: user 5.18 s, sys: 73.3 ms, total: 5.26 s
Wall time: 5.3 s


In [239]:
prediction[:10]

array([  43.28182696,  -72.1776449 ,    7.26750592,   21.38554593,
          4.73059485,  -69.06735374,   24.30899387,   39.36748891,
       -136.99463175,   19.87488798])

In [241]:
best_model.score(Z, r)

0.8895993005101471

#### SVM

classification

In [26]:
svm_param_grid = {'kernel':('linear', 'rbf'),
                  'C':[1, 10]
                 }

In [66]:
%%time
clf = SVC(random_state=0)
CV_clf = GridSearchCV(estimator=clf, param_grid=svm_param_grid, cv= 5)
CV_clf.fit(X, y)
best_params = CV_clf.best_params_
best_model = CV_clf.best_estimator_
prediction = best_model.predict(X)

CPU times: user 236 ms, sys: 3.59 ms, total: 239 ms
Wall time: 239 ms


regression

In [69]:
%%time
lr = SVR()
CV_lr = GridSearchCV(estimator=lr, param_grid=svm_param_grid, cv= 5)
CV_lr.fit(Z, r)
best_params = CV_lr.best_params_
best_model = CV_lr.best_estimator_
prediction = best_model.predict(Z)

CPU times: user 755 ms, sys: 5.11 ms, total: 760 ms
Wall time: 760 ms


In [70]:
best_params, best_model, prediction[:10]

({'C': 10, 'kernel': 'linear'},
 SVR(C=10, kernel='linear'),
 array([  55.07942609,  -31.41343535,   37.02373867,   50.39994597,
          -6.60878732,  -83.00622185,   63.80482698,   44.09822181,
        -141.26588642,   34.70977182]))